### ISSUE TITLE
Logout a user

### ISSUE THREAD

**Issue by fdgneto** [keitaroinc/ckanext-keycloak#12]
Hello, 
i'm using this plugin to integrate keycloak into ckan. i just ran into the problem that there is no logout. How can I log out a user?

**Comment by tino097** [comment]
@fdgneto it should use core `logout` functionality. 

What CKAN version are you using and is there any errors or the user is still logged in ?

**Comment by fdgneto** [comment]
Thanks for the quick reply @tino097 .
At the moment i'm using logout core to log out but it doesn't work. The flow runs normally with the redirects to the correct pages but the user is still logged in. 
There are no problems.
My version of ckan is 2.10.

**Comment by tino097** [comment]
It could be a bug as the CKAN 2.10+ the `flask-login` is implemented.

**Comment by fdgneto** [comment]
Ok i understand.
And what would be a possible solution to this?

**Comment by tino097** [comment]
If you able to provide a PR with the fix it would be great

**Comment by fdgneto** [comment]
its possible to get the user token ?
I'm trying to use the python-keycloak to logout and for that i need the token.
https://python-keycloak.readthedocs.io/en/latest/modules/openid_client.html#logout

**Comment by fdgneto** [comment]
The workaround I came up with was to redirect the user to the keycloak logout page by editing the ckan core logout function.

keycloak logout url -> `http://{domain-name}/auth/realms/{realm-name}/protocol/openid-connect/logout?post_logout_redirect_uri=encodedRedirectUri`


```
def logout() -> Response:
    for item in plug.PluginImplementations(plug.IAuthenticator):
        response = item.logout()
        if response:
            return response
    user = current_user.name
    if not user:
        return h.redirect_to('user.login')

    came_from = request.args.get('came_from', '')
    logout_user()

    field_name = config.get("WTF_CSRF_FIELD_NAME")
    if session.get(field_name):
        session.pop(field_name)

    if h.url_is_local(came_from):
        return h.redirect_to(str(came_from)) 
    
    server_domain=config.get('ckanext.keycloak.domain_server', None)
    realm=config.get('ckanext.keycloak.realm_name', None)
    client_id=config.get('ckanext.keycloak.client_id', None)
    redirect_url=h.url_for(u"home.index", _external=True)
    encoded_redirect_url = quote(redirect_url, safe='')
    return redirect_to(f"{server_domain}/auth/realms/{realm}/protocol/openid-connect/logout?post_logout_redirect_uri={encoded_redirect_url}&client_id={client_id}")
```

**Comment by tino097** [comment]
Hey @fdgneto 
this looks good, but you dont need to edit the core`logout` functionality
You could create a custom endpoint for `logout` in this extension, and maybe provide a PR for that 

Similar as it is done [here](https://github.com/keitaroinc/ckanext-saml2auth/blob/main/ckanext/saml2auth/views/saml2auth.py#L343-L347)

**Comment by blagojabozinovski** [comment]
@fdgneto the user is logged out from CKAN but not from Keycloack?

**Comment by fdgneto** [comment]
@blagojabozinovski, yes, in fact that was the problem, I logged out (ckan) but when I refreshed the page, since it still had the keycloak credentials saved in the session, logged back in.
